language: python
python:
  # - "3.3"
  # - "3.2"
  # - "2.7"
  # - "2.6"
  # - "pypy"
  - "2.5"
install:
  # Build/test dependencies
  - pip install -r requirements.txt --use-mirrors
before_script:
  - python testusage.py write
script:
  - python testusage.py scanme
