language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

# Install Flake8
install:
  - pip install -r requirements.txt --use-mirrors
script:
  # Test scripts against Flake8
  - flake8 --max-complexity 10 .

  # Run the examples
  - python examples/scanning.py
  - python examples/stored.py
  - python examples/exceptions.py
